### ISSUE TITLE
[Question] About using AWS lambda  case

### ISSUE THREAD

**Issue by satoru02** [WayneChang65/linebot2#3]
Hello! Thanks for maintaining the library.

I use linebot by boybundit for my private Line App.  But I found this forked version, then i started this version's library(linebot2) because this ver's is currently maintained. 
I am building a Line bot server in Lambda. So, in the example directory, can I submit a pull request for a use case for using this library in Lambda?

**Comment by WayneChang65** [comment]
Yes. You are welcome to PR. Nowadays, serverless services are very popular and it is convenient for developers to concentrate on bot development, so your contribution will help. I'm waiting for it. Thanks. :)
