### ISSUE TITLE
[QUESTION] Is this package also support sending flex message?

### ISSUE THREAD

**Issue by Uryaaa** [WayneChang65/linebot2#9]
![1634199380019](https://user-images.githubusercontent.com/61571823/137278616-e73b7fe3-ea9c-423b-b754-a07c76541873.jpg)
Something like this

**Comment by WayneChang65** [comment]
Yes, no problem for that.
You could send a message object like { type: 'flex' ...} for a flex message.
I've been using it on my [tosmm project](https://github.com/WayneChang65/tosmm) and screenshot as below. Please check it out.
I think linebot2 SDK is easier than LINE official. Try and enjoy it. :)


<img width="315" alt="截圖 2021-10-14 16 27 42" src="https://user-images.githubusercontent.com/33888917/137280305-29ce8d6a-081b-46ba-9762-f406bb8100e9.png">

<img width="352" alt="截圖 2021-10-14 16 28 30" src="https://user-images.githubusercontent.com/33888917/137280455-425d2ba5-8de1-44ce-b21e-5c3de92cddcd.png">
